name: my-workflow

on:
  push:

jobs:
  build-linux:
    name: my-job
    runs-on: ubuntu-latest
    if: github.ref == 'refs/head/master'
    steps:
      # ...
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - name: Download packages
        run: bun install

      # Create release
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.head_commit.message }}
          release_name: ${{ github.event.head_commit.message }}
          body: |
            Test Release v1.0.0
          draft: false
          prerelease: false
